### PR TITLE
clean up error handling

### PR DESCRIPTION
**Pull request by bgoldman**
Addresses https://github.com/crocodoc/php-box-view/issues/4#issuecomment-128628179

/review @codyebberson

### CODE REVIEW

**Comment by stof** [comment]
I don't think this addresses it. If we are asking for the status of a document, we don't want an exception to be thrown at all because of ``status=error`` in the document.

what is the reason to throw an exception here when the document is in error status ?

**Comment by bgoldman** [comment]
With this code, an exception wont be thrown when checking the status of a document where status=error. Did you test it?

**Comment by bgoldman** [comment]
Nevermind, my bad. Try now.

**Comment by stof** [comment]
Well, the only reason it does not throw is because status=error does not expose the reason of the error anymore contrary to the Crocodoc API (and IIRC, there is a card in Trello asking to expose it again).

Once again, why would a document in the error state throw exceptions when loading its properties ?

**Comment by Siraris** [comment]
Hey guys, I'm actually running into this issue now (I actually opened an issue for it before seeing this PR existed).  I'd really love to adopt the SDK, but this is preventing me from doing so as it's generating a fatal error due to the timeout.  Do you guys have any insight as to why the API is timing out btw?  Seems strange that it would just timeout and not generate a response, instead of responding with a throttling message, or some other issue?  

Would really love to get this resolved, or any insight on a path to do so!

**Pull request merged**
